const data = {
    products : [
        {
            id : 1,
            name : 'slim shirt',
            brand : 'Nike',
            price : 120,
            description : 'High quality product',
            image : '/Images/slim shirt.jpeg',
            rating : 4.5,
            numReviews : 23,
            countInStock : 22,
            category : 'shirt',
        },
        {
            id : 2,
            name : 'short pant',
            brand : 'Adidas',
            price : 80,
            description : 'High quality product',
            image : '/Images/short pant.jpeg',
            rating : 3.5,
            numReviews : 23,
            countInStock : 22,
            category : 'pants',
        },
        {
            id : 3,
            name : 'long pant',
            brand : 'Nike',
            price : 233,
            description : 'High quality product',
            image : '/Images/long pant.jpeg',
            rating : 4.5,
            numReviews : 23,
            countInStock : 22,
            category : 'pants',
        },
        {
            id : 4,
            name : 'fit shirt',
            brand : 'Puma',
            price : 120,
            description : 'High quality product',
            image : '/Images/images (17).jpeg',
            rating : 4.0,
            numReviews : 23,
            countInStock : 22,
            category : 'shirts',
        },
        {
            id : 5,
            name : 'big shirt',
            brand : 'Nike',
            price : 120,
            description : 'High quality product',
            image : '/Images/big shirt.jpeg',
            rating : 3,
            numReviews : 23,
            countInStock : 22,
            category : 'shirts',
        },
    ]
}

export default data;